### ISSUE TITLE
Panic if can't find OS wordlist

### ISSUE THREAD

**Issue by benliepert** [Samyak2/toipe#25]
On Arch Linux, guess I don't have an OS wordlist: 

`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ToipeError { msg: "No such file or directory (os error 2)" }', /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/toipe-0.4.0/src/main.rs:9:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`
Could print a warning or just use the default word list? I can write a fix for this since I want an excuse to do rust

**Comment by Samyak2** [comment]
Good catch.

Although, I don't think printing a warning or using the default word list is a good idea. The same error can be printed better with some more context (example: `Error reading the given word list: No such file or directory (os error 2)`).

You can open a PR for this if you want to

**Comment by benliepert** [comment]
If you look at my latest commit (benliepert/toipe@cd0951e6e33b39ea2c02fc9aa28cb855216faad2) you can see what I did to fix this. But, it's ugly as the match statement is repeated. Is this how you would fix it? can you see a way to consolidate the match statements?
I tried this:
```
pub fn new(config: ToipeConfig) -> Result<Self, ToipeError> {
        fn create_toipe_wordlist_error(e: std::io::Error) -> ToipeError {
            let mut toipe_error = ToipeError::from(e);
            toipe_error.msg = "Error reading the given word list: ".to_string() + &toipe_error.msg;
            toipe_error
        }
        let word_selector: Box<dyn WordSelector> = {
            let mut word_selector_result_option: Option<_>; //: Result<RawWordSelector<std::fs::File>, std::io::Error>;
            if let Some(wordlist_path) = config.wordlist_file.clone() {
                word_selector_result_option = Some(RawWordSelector::from_path(PathBuf::from(wordlist_path)));
            } else if let Some(word_list) = config.wordlist.contents() {
                word_selector_result_option = Some(RawWordSelector::from_string(word_list.to_string()));
            } else if let BuiltInWordlist::OS = config.wordlist {
                word_selector_result_option = Some(RawWordSelector::from_path(PathBuf::from(OS_WORDLIST_PATH)));
            } else {
                // this should never happen!
                // TODO: somehow enforce this at compile time?
                return Err(ToipeError {
                    msg: "Undefined word list or path.".to_string(),
                });
            };

            match word_selector_result_option {
                Some(thing) => {
                    match thing {
                        Ok(rws) => Box::new(rws),
                        Err(e) => return Err(create_toipe_wordlist_error(e)),
                    }
                }
                None => {
                    return Err(ToipeError {
                        msg: "This is logically impossible to occur".to_string(),
                    });
                }
            }
 
        };
```
but I get this compilation error:
```
error[E0308]: mismatched types
  --> src/lib.rs:79:52
   |
79 |                 word_selector_result_option = Some(RawWordSelector::from_string(word_list.to_string()));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `File`, found struct `std::io::Cursor`
   |
   = note: expected enum `Result<RawWordSelector<File>, _>`
              found enum `Result<RawWordSelector<std::io::Cursor<std::string::String>>, _>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `toipe` due to previous error
```
it's not making sense to me because it looks like from_string() and from_path() both return the same type.

**Comment by Samyak2** [comment]
> it's not making sense to me because it looks like from_string() and from_path() both return the same type.

While both of them are `RawWordSelector`s, they are not the same type because `RawWordSelector` is a [generic type](https://github.com/Samyak2/toipe/blob/378208ad1a5ca13e5acb7c2c0066018d577a5393/src/textgen.rs#L64) (see the [rust book's page on this](https://doc.rust-lang.org/book/ch10-01-syntax.html) if you haven't come across it before). `from_path` gives a [`RawWordSelector<File>`](https://github.com/Samyak2/toipe/blob/378208ad1a5ca13e5acb7c2c0066018d577a5393/src/textgen.rs#L198) whereas `from_string` gives a [`RawWordSelector<Cursor<String>>`](https://github.com/Samyak2/toipe/blob/378208ad1a5ca13e5acb7c2c0066018d577a5393/src/textgen.rs#L212). You can think of the `T` in `RawWordSelector<T>` as a type "parameter" and the `File` and `Cursor<String>` as the type "argument" that is passed to the parameter.

---

```rust
        fn create_toipe_wordlist_error(e: std::io::Error) -> ToipeError {
            let mut toipe_error = ToipeError::from(e);
            toipe_error.msg = "Error reading the given word list: ".to_string() + &toipe_error.msg;
            toipe_error
        }
```

IMO this isn't a nice way to do it (as a free function that is) because this operation is about a `ToipeError` so this function should be associated with that (in one of its `impl` block). The `"Error reading the given word list: "` string can then be a parameter of the function. So the usage would become `Err(ToipeError::from_erro("Error reading the given word list: "))`. The error string would be repeated, but that's ok for an initial solution.

An improvement over that would be to have this function on a `Result<_, ToipeError>`. I'm not entirely sure if this is possible without introducing a new trait, but it will improve the code as you can just call the function on the `Result` returned by the if-else block.

**Comment by Samyak2** [comment]
> I agree about the ToipeError, but won't I have to pass in the `std::io::Error` to the function as well? Something like `ToipeError::from_error(e, "[context]")`.

My bad, yes you will have to.

> Could also add a separate function `ToipeError::add_context(string)` that would just prefix the ToipeError's msg with the string passed in.

This is a good idea! Although I would write it as `fn with_context(self, msg: &str) -> Self` so that it can be used as `ToipeError::from(e).with_context("[context]")`.

**Comment by benliepert** [comment]
Created a PR for the simple approach (no function to handle a result) [here](https://github.com/Samyak2/toipe/pull/26).
I can edit it how you'd like (squash commits? change the title? This is my first github PR)
