### ISSUE TITLE
not working with cusotm words list 

### ISSUE THREAD

**Issue by SamDc73** [Samyak2/toipe#30]
I have a txt file 243 word and when i try to open it with topie using the -f flag it shows nothing inside the app (I'm sure about the path and i tried absolute path too)

**Comment by Samyak2** [comment]
Could you check the contents of the word list? It must satisfy these assumptions - https://docs.rs/toipe/latest/toipe/textgen/struct.RawWordSelector.html#assumptions. There's no check for it currently, so Toipe simply skips over words that don't satisfy it instead of showing an error.

We can debug it together if you can post the file or a snippet of it here.
