### ISSUE TITLE
Add some more features

### ISSUE THREAD

**Issue by kunal1234523** [Samyak2/toipe#32]
There are some feature, you may add to make it more usable,
1. ctrl + backspace should delete the previous typed characters until a space is encountered.
2. Statistics of your previous typing tests

**Comment by Samyak2** [comment]
Hey @kunal1234523! Thank you for the suggestions.

> ctrl + backspace should delete the previous typed characters until a space is encountered.

There was an issue for this already (#18) and `ctrl-w` has been added already and is available in `v0.4.0`. [`ctrl-backspace` could not be implemented](https://github.com/Samyak2/toipe/issues/18#issuecomment-1088600315).

> Statistics of your previous typing tests

This is great idea. It has been suggested before (#11).

---

I could not find time to work on this in the past couple of months, so if you know some Rust, you can try contributing too!

---

I'm closing this issue for now since there are other issues specific to the features you requested. Feel free to open more issues if you have other suggestions!
